apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJnaGNyLmlvIjogewoJCQkiYXV0aCI6ICJiV1Z5WVcxcFpIUmxjM1E2WjJod1gzTm1aRnAwYkZWV1Z6aG1ibm81UjNwM1dUbE1OMm93UVVkYWVVeE9hekZvVVZoU1RBPT0iCgkJfQoJfSwKCSJjcmVkc1N0b3JlIjogImRlc2t0b3AiLAoJImN1cnJlbnRDb250ZXh0IjogImRlc2t0b3AtbGludXgiCn0=
type: kubernetes.io/dockerconfigjson
